apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petite-maison-backend-hpa
  namespace: petite-maison-epouvante
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petite-maison-backend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
