apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: collector-frontend-hpa
  namespace: collector-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collector-frontend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
